plugins: 
  - test_plugin_one:
      path: "plugins/test_plugin_one"
      name: "TestPluginOne"

  - test_plugin_two:
      path: "plugins/test_plugin_two"
      name: "TestPluginTwo"


documents:
  - document_one:
    plugin: "test_plugin_one"
    uri: "uri"
    

