[project]
name = "RagDocumentLoader"
version = "0.1.0"
dependencies = [
    "dotenv>=0.9.9",
    "google-auth>=2.45.0",
    "google-cloud-aiplatform>=1.132.0",
    "gspread>=6.2.1",
    "pandas>=2.3.3",
    "psycopg2-binary>=2.9.11",
    "pyyaml>=6.0.3",
    "vertexai>=1.43.0",
]
